Updates to acquire auth tokens for GHE LFS operations.
liberapay/git-lfs-fetch.py pull request #5
Opened 2017-02-27 21:20 UTC by lhasadad

Updates for GHE token acquisition.

list of changes:

1. cleaned up a few pep 8 issues
2. adjusted some imports that were problematic in eclipse pydev environment. seem to work fine in use.
3. in get_lfs_endpoint_url, adjust it to not overload the 'url' variable 
4. adjusted /objects/batch call to pick up the initial token to use for that call in GHI
5. adjusted the downloads to use the auth tokens associated with the items to download.
6. Added extra debug lines.
7. Changed some code to allow for possible running on windows system (though was not able to get it to work because the behavior of the os.rename was 'odd' (the rename file would disappear before the copy to working dir happened, needs further work to make work right)

Note, I did not update any of the distro version stuff.  I could but figured that might be something you would rather do.

Let me known if you want any changes or have questions.

2017-02-28 16:04 UTC, Changaco requested changes

2017-02-28 16:04 UTC, Changaco commented on git_lfs/__init__.py
> +    _verbose = verbose
Please remove this and keep all the log messages in the top `fetch()` function.

2017-02-28 16:04 UTC, Changaco commented on git_lfs/__init__.py
> +                print ('cache file name: ' + dst1)
Please remove the spaces between `print` and its arguments.

2017-02-28 16:04 UTC, Changaco commented on git_lfs/utils.py
> +        os.link(source, link_name)
It would be better to always try `os.link` and fall back to copying. Trying to guess whether linking will work by looking at the platform is unreliable.

Moreover a warning should be emitted if linking isn't supported, ideally.

2017-02-28 16:04 UTC, Changaco commented on git_lfs/__init__.py
> +from utils import force_link, ignore_missing_file, in_dir, TempDir, TempFile
Please revert the import modifications. If a tool you're using can't handle relative imports, fix it, don't change the imports.

2017-02-28 16:23 UTC, lhasadad commented on git_lfs/utils.py
> +        os.link(source, link_name)
agreed.  Seems better.  for now I can pull that one.  not needed for what I am doing but it shows up  as an unresolvable function in 2.7 level of Python on windows (so will throw an python exception there.  I like the idea of the falback.

2017-02-28 16:23 UTC, lhasadad commented on git_lfs/__init__.py
> +                print ('cache file name: ' + dst1)
Will do.  my bad there.

2017-02-28 16:25 UTC, lhasadad commented on git_lfs/__init__.py
> +    _verbose = verbose
Can we discuss this one.  a little.   I was trying to make it so any function in the __init__.py could reference the verbose setting (since its always entered through fetch) without having to pass it around.   If you still want it removed I can (or I could convert all other items to use that variable so there is no confusion (I only referenced it where I added it. )   Let me know if you still want it out If so I will need to refactor a few spots that refer to it.

2017-02-28 16:29 UTC, lhasadad commented on git_lfs/__init__.py
> +from utils import force_link, ignore_missing_file, in_dir, TempDir, TempFile
This was causing an error trying to debug on Eclipse.   with the import adjusted it did not error out there or in actual use.   I am thinking the inclusion of the relative reference is unneeded with the packaging you have there.   I will do what you wish but the functions were properly called with the . removed.  please let me know if you still want it restored.  if so I will restore to original code.
FYI I tested the modified code on a linux system using 2.7 python and encountered no error.

2017-02-28 18:28 UTC, lhasadad commented
@Changaco I responded with some questions and throughts.  let me know what you think and I will proceed.

2017-02-28 22:12 UTC, lhasadad commented
fyi, I noticed a problem I had introduced on the urlsplit handling (url_split.host vs url_split.hostname (correct))  That will be in the next commit against the branch.

2017-03-01 09:28 UTC, Changaco commented on git_lfs/__init__.py
> +from utils import force_link, ignore_missing_file, in_dir, TempDir, TempFile
I won't drop relative imports in this project just because some tools don't handle them properly. Please restore them.

2017-03-01 09:29 UTC, Changaco commented on git_lfs/__init__.py
> +    _verbose = verbose
The proper way to allow every function to log messages would be to use a global logger from the standard `logging` module, definitely not to use the `global` keyword (that's pretty much never a good idea). For now I suggest keeping the log messages contained to the top function, it's simpler and relatively clean.

2017-03-01 12:50 UTC, lhasadad commented on git_lfs/__init__.py
> +from utils import force_link, ignore_missing_file, in_dir, TempDir, TempFile
Will change back and commit.  thanks.

2017-03-01 12:50 UTC, lhasadad commented on git_lfs/__init__.py
> +    _verbose = verbose
removed.  will pass along value to called routines if needed.

2017-03-01 12:51 UTC, lhasadad commented on git_lfs/utils.py
> +        os.link(source, link_name)
removed the  new code left the os.link for now.

2017-03-01 13:00 UTC, lhasadad commented
updated with new commit to address issues raised.

2017-03-01 17:03 UTC, Changaco approved these changes
Back to you @lhasadad. Please confirm that the changes I've made look okay to you.

2017-03-01 18:32 UTC, lhasadad commented
Looks, good will give it a try in our environment and respond shortly

2017-03-01 18:45 UTC, lhasadad commented
Tried it, looks good and did as expected.

2017-03-01 19:11 UTC, merged